name: CMake CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Configure CMake
      run: cmake -B build -DMINIDYN_BUILD_TESTS=ON

    - name: Build C++ project
      run: cmake --build build --config Release

    - name: Run Tests
      working-directory: build
      run: ctest --output-on-failure
